name: React Frontend CI

on:
  push:
    branches: [ "main", "feat-devops" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      working-directory: ./client
      run: npm install

    - name: Test Build
      working-directory: ./client
      run: npm run build
